version: '2'
services:
  app:
    image: aakail11/kailio:dev
    volumes:
      - ./:/app
      - ./uploads:/app/kailio/static/uploads
    working_dir: /app
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - db
    command: run --reload
    environment:
      - FLASK_DEBUG=True
      - TEMPLATES_AUTO_RELOAD=True
      - SQLALCHEMY_DATABASE_URI=postgresql://kailio:testing@db/kailio
      - SECRET_KEY=alskdfasdfna
      - SECURITY_PASSWORD_SALT=mysalttest
      - MAIL_PORT=465
      - MAIL_SERVER=mail.privateemail.com
      - MAIL_USERNAME=andrew@kail.io
      - MAIL_PASSWORD=KL#29ndrwk
  db:
    image: postgres:12
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: kailio
      POSTGRES_PASSWORD: testing
    #networks:
      #- databases
