"""add hits to page

Revision ID: b5701277bb59
Revises: 333a67a5bd77
Create Date: 2020-07-29 00:42:49.653982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5701277bb59'
down_revision = '333a67a5bd77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('hits', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'hits')
    # ### end Alembic commands ###
