"""enable comments

Revision ID: c14a28ced33e
Revises: 2d0e5c6cc5c3
Create Date: 2020-08-06 20:16:28.173931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c14a28ced33e'
down_revision = '2d0e5c6cc5c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pages', sa.Column('comments_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pages', 'comments_enabled')
    # ### end Alembic commands ###
